[package]
name = "moelyrics"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.19.0"
ego-tree = "0.6.2"
regex = "1.10.4"
reqwest = "0.12.4"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
clap = { version = "4.5.4", features = ["derive"] }
url = "2.5.0"